upstream auth_app_cluster {
    server <Your Node2 IP>:3000 max_fails=3 fail_timeout=3s;
    server <Your Node1 IP>:3000 max_fails=3 fail_timeout=3s backup;
    keepalive 400;
}

server {
    listen 443 ssl;
    server_name <>your_domain_or_ip>;
    ssl_certificate /opt/init/sslCert.cer;
    ssl_certificate_key /opt/init/sslKey.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305';
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 1d;

    location / {
        proxy_pass http://auth_app_cluster;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # 'off' is safer if your app handles its own redirects
        proxy_redirect off;
    }
}
